### ISSUE TITLE
renderViewEntity ClassCastException

### ISSUE THREAD

**Issue by TheCyberBrick** [zlainsama/CleanView#1]
Crash log: https://gist.github.com/TheCyberBrick/b745ea8e6de1afdc977ff28e5e6a0d49

The mod crashes when The Betweenlands mod is installed because the renderViewEntity is replaced by an entity that does not extend EntityLivingBase.

https://github.com/zlainsama/CleanView/blob/master/src/main/java/lain/mods/cleanview/Proxy.java#L48
You probably intended to catch the ClassCastException there, but since ClassCastException does not extend Error it crashes

**Comment by zlainsama** [comment]
Okay, i will update it soon. The code was from pretty long ago. I guess renderViewEntity can be non EntityLivingBase now.
