### ISSUE TITLE
[1.16.5-Forge] Mark mod as client side only, makes server "incompatible" in server list.

### ISSUE THREAD

**Issue by Gbergz** [zlainsama/CleanView#14]
Title ^

If mod is missing on server it makes the server ping "Incompatible FML Modded Server".
If possible, mark mod as client only.

![image](https://user-images.githubusercontent.com/26634554/119142325-a8f46c80-ba46-11eb-947f-4f96413ce50c.png)

Thanks,
**-** Gbergz

**Comment by zlainsama** [comment]
my bad, I had it already in the code but have not released it, I will release a new version soon.
