### ISSUE TITLE
[1.20.5 Fabric] Crash with RuntimeException on 'client' stage

### ISSUE THREAD

**Issue by smowtenshi** [zlainsama/CleanView#18]
First I noticed it with my modpack, but I'm able to reproduce it on clean 1.20.5 instance.
(It seems to work just fine on 1.20.4 though.)

Crash report: https://gist.github.com/smowtenshi/9d09edc49f4765e14215562e901dc1b3

- Fabric Loader: 0.15.10
- Fabric API: 0.97.8+1.20.5
- CleanView: 1.20.5-v1-fabric

**Comment by zlainsama** [comment]
fixed in 1.20.5-v1a-fabric, thanks for the report.
