### ISSUE TITLE
This mod does not seem to work for the pack 'Dunegons, Dragons, and Space Shuttles. I know this likely isnt your fault but I really want to figure out why this is happening.

### ISSUE THREAD

**Issue by OmaiGrundles** [zlainsama/CleanView#7]
I think one of the mods in the pack may also be affecting the particle effects and overwriting your mod, but for the life of me I cant figure it out. I was so excited when I found out about this mod and was equally crushed when I couldn't get it to work.

Also, would be nice if when you hit the toggle that it gives a chat message telling that the toggle was successful.

**Comment by zlainsama** [comment]
Hmm, sorry to hear about that.
The thing is, I'm still using a quite old PC, and that pack is pretty big for my PC to handle.
It would help a lot if you can single out the mods that is causing incompatibilities with CleanView so that I can test them and find out the actual cause on my end.

**Comment by OmaiGrundles** [comment]
I'm going to try to figure out what mod it is but it may take quite a while, as I'm no expert in this. I will note that it feels like the 'potion sparklies' in your face in this pack seems a bit higher than vanilla, but I can't be sure.

My first thought was InfernalMobs (its the mod that creates miniboss mobs with tons of potion effects and such on them) but it doesn't seem like that's the culprit.

Is it possible to force your mod to apply its effects last in the 'load order'? is that even a thing with forge? Or maybe some sort of info we could get from logs?

**Comment by zlainsama** [comment]
My mod modifies a color value on player so that the game simply no longer renders them, it does not alter any rendering stuff. So load order shouldn't matter.
If a mod displays those particles then it must be getting the real color information from a different source.
You can removing/testing half mods at once, this way it's much faster.

**Comment by OmaiGrundles** [comment]
I think I have found the mod responsible. Its called RandomPatches.

~~It has something in its configs about 'toggling/removing potion glow' that I'm unable to figure out what it actually does. Unfortunately, disabling/enabling those functions does not solve the problem.~~

Setting Line 142 to false on RandomPatches config "Fixes MC-10369 (server-side particle spawning not creating particles for clients) and MC-93826 (breeding hearts only showing once instead of all of the time an animal can breed)." allows CleanView to work!

**Comment by zlainsama** [comment]
Hmm, it seems your feeling about those particles been higher than vanilla might be true.
I have looked into the patch applied by that mod and the original mod that patch came from.
It involves actually sending "spawn particle" packets to client when particles are spawned on server side.
Which in the case of entities' potion particles, they are usually spawned only on client side using a color value synchronized from server, this color value was modified by my mod on client side to make them not spawn.
So you are having two sources of particles on your player, that makes it higher than vanilla.

**Comment by zlainsama** [comment]
Fixed in RandomPatches 1.12.2-1.21.0.0.
